import React from 'react';
import ReactMarkdown from 'react-markdown';
import { AnalysisResult } from '../types';
import { ExternalLink, Leaf, Sprout, FileText, ArrowRight, BookOpen, ShieldCheck } from 'lucide-react';

interface Props {
  result: AnalysisResult;
  loading: boolean;
}

const AnalysisView: React.FC<Props> = ({ result, loading }) => {
  if (loading) {
    return <AnalysisSkeleton />;
  }

  if (!result.recommendation) {
     return <EmptyState />;
  }

  const isOfficialSource = (uri: string) => {
    return uri.includes('.gov.bd') || uri.includes('barc') || uri.includes('srdi') || uri.includes('brri') || uri.includes('bari');
  };

  return (
    <div className="bg-white rounded-2xl shadow-xl shadow-earth-900/5 border border-earth-200 overflow-hidden flex flex-col h-full animate-in fade-in duration-500">
      <div className="bg-gradient-to-r from-agri-50 to-white px-8 py-6 border-b border-agri-100/50 flex justify-between items-center">
        <div>
            <h2 className="text-xl font-bold text-agri-900 flex items-center gap-2">
            <Leaf className="w-5 h-5 text-agri-600" />
            Soil Analysis Report
            </h2>
            <p className="text-sm text-agri-700/70 mt-1">Generated by AI based on regional data</p>
        </div>
        <div className="hidden sm:flex items-center gap-2 text-xs font-medium text-agri-600 bg-agri-100 px-3 py-1 rounded-full">
            <Sprout className="w-3 h-3" />
            Insights Ready
        </div>
      </div>
      
      <div className="p-8 overflow-y-auto custom-scrollbar flex-grow bg-white">
        <div className="prose prose-earth prose-sm sm:prose-base max-w-none 
            prose-headings:font-bold prose-headings:text-earth-800 prose-headings:tracking-tight
            prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg
            prose-p:text-earth-600 prose-p:leading-relaxed
            prose-li:text-earth-600
            prose-strong:text-earth-900 prose-strong:font-bold
            prose-blockquote:border-l-4 prose-blockquote:border-agri-300 prose-blockquote:bg-agri-50 prose-blockquote:px-4 prose-blockquote:py-1 prose-blockquote:rounded-r-lg prose-blockquote:not-italic
        ">
          <ReactMarkdown>{result.recommendation}</ReactMarkdown>
        </div>

        {result.sources && result.sources.length > 0 && (
          <div className="mt-12 pt-8 border-t border-earth-100">
            <div className="flex items-center gap-2 mb-4">
                <BookOpen className="w-4 h-4 text-earth-400" />
                <h4 className="text-xs font-bold text-earth-500 uppercase tracking-wider">References & Grounding</h4>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {result.sources.map((source, idx) => {
                const official = isOfficialSource(source.uri);
                return (
                    <a 
                    key={idx} 
                    href={source.uri} 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className={`flex items-start gap-3 p-3 rounded-lg border transition-all group relative overflow-hidden
                        ${official 
                            ? 'bg-agri-50/50 border-agri-100 hover:border-agri-300 hover:bg-agri-50' 
                            : 'bg-earth-50 border-earth-100 hover:bg-white hover:border-earth-300'}`}
                    >
                    <div className={`p-1.5 rounded-md border flex-shrink-0 ${official ? 'bg-white border-agri-200 text-agri-600' : 'bg-white border-earth-200 text-earth-500'}`}>
                        {official ? <ShieldCheck className="w-3 h-3" /> : <ExternalLink className="w-3 h-3" />}
                    </div>
                    <div className="overflow-hidden min-w-0">
                        <p className={`text-xs font-bold truncate transition-colors ${official ? 'text-agri-900' : 'text-earth-800'}`}>
                            {source.title || 'Source Reference'}
                        </p>
                        <p className={`text-[10px] truncate mt-0.5 ${official ? 'text-agri-600' : 'text-earth-500'}`}>
                            {new URL(source.uri).hostname}
                        </p>
                    </div>
                    <ArrowRight className={`w-3 h-3 ml-auto transform group-hover:translate-x-1 transition-all ${official ? 'text-agri-400' : 'text-earth-300'}`} />
                    </a>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

const AnalysisSkeleton = () => (
    <div className="bg-white rounded-2xl shadow-lg border border-earth-200 overflow-hidden flex flex-col h-full animate-pulse">
        <div className="bg-earth-50 px-8 py-6 border-b border-earth-100">
            <div className="h-6 w-48 bg-earth-200 rounded mb-2"></div>
            <div className="h-4 w-32 bg-earth-100 rounded"></div>
        </div>
        <div className="p-8 space-y-6">
            <div className="space-y-3">
                <div className="h-4 w-full bg-earth-100 rounded"></div>
                <div className="h-4 w-[90%] bg-earth-100 rounded"></div>
                <div className="h-4 w-[95%] bg-earth-100 rounded"></div>
            </div>
            <div className="space-y-3 pt-4">
                <div className="h-5 w-40 bg-earth-200 rounded mb-2"></div>
                <div className="h-4 w-full bg-earth-100 rounded"></div>
                <div className="h-4 w-full bg-earth-100 rounded"></div>
            </div>
            <div className="grid grid-cols-3 gap-4 pt-4">
                <div className="h-24 bg-earth-100 rounded-lg"></div>
                <div className="h-24 bg-earth-100 rounded-lg"></div>
                <div className="h-24 bg-earth-100 rounded-lg"></div>
            </div>
        </div>
    </div>
);

const EmptyState = () => (
    <div className="flex flex-col items-center justify-center h-full p-8 bg-earth-50/50 rounded-2xl border-2 border-dashed border-earth-200 text-center">
        <div className="bg-white p-4 rounded-full shadow-sm mb-6">
            <FileText className="w-12 h-12 text-earth-300" />
        </div>
        <h3 className="text-lg font-bold text-earth-800 mb-2">Ready to Analyze</h3>
        <p className="text-earth-600 max-w-sm mb-8 text-sm leading-relaxed">
            Select an Agro-ecological Zone from the explorer or input specific soil data to generate a detailed agronomic report.
        </p>
        <div className="flex gap-2 text-xs text-earth-400 font-medium bg-earth-100 px-4 py-2 rounded-full">
            <span>Powered by Gemini 2.5</span>
            <span>&bull;</span>
            <span>Official BD Data</span>
        </div>
    </div>
);

export default AnalysisView;